from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional

from brikie.config.types import BusEvent

if TYPE_CHECKING:
    from brikie.bricks.interface.event_bus import InternalEventBusBrick
    from brikie.bricks.logging.diagnostics import DiagnosticsCollectorBrick
    from brikie.bricks.soul.dreamer import Dreamer
    from brikie.bricks.soul.foreman import Foreman

logger = logging.getLogger(__name__)

MAX_CONSECUTIVE_FAILURES = 5
SAFETY_PAUSE_SECONDS = 60
IDLE_CYCLE_PAUSE_SECONDS = 2.0
EVALUATION_TIMEOUT_SECONDS = 10.0


@dataclass
class Proposal:
    """A proposal generated by the Dreamer and evaluated by Foreman."""

    title: str = ""
    description: str = ""
    impact: str = "low"
    complexity: str = "low"
    proposal_id: str = ""
    status: str = "pending"


@dataclass
class AFKCycleResult:
    """Result of a single AFK negotiation cycle."""

    cycle_number: int = 0
    proposals_count: int = 0
    approved_count: int = 0
    executed_count: int = 0
    failed_count: int = 0
    duration_seconds: float = 0.0
    consecutive_failures: int = 0


def _now() -> float:
    import time
    return time.time()


class AFKProtocolEngine:
    """Orchestrates the Dreamer→Foreman AFK negotiation loop.

    The loop runs in three stages:
    1. DREAM — Dreamer reviews logs and formulates proposals
    2. EVALUATE — Foreman evaluates proposals against constraints
    3. EXECUTE — Foreman executes approved proposals

    Invariants:
    - Max 3 approval attempts per proposal
    - Max 3 sub-delegation depth per execution
    - 300s timeout per sub-task
    - Safety pause after 5 consecutive failures
    """

    def __init__(
        self,
        event_bus: InternalEventBusBrick,
        dreamer_soul: Optional[Dreamer] = None,
        foreman_soul: Optional[Foreman] = None,
        diagnostics: Optional[DiagnosticsCollectorBrick] = None,
        on_execute: Optional[Callable[[str, Dict[str, Any]], Any]] = None,
        dreamer_propose: Optional[Callable[[str, int], Any]] = None,
        on_stage: Optional[Callable[[str, str], Any]] = None,
        evaluation_timeout: float = EVALUATION_TIMEOUT_SECONDS,
    ) -> None:
        """Args beyond the souls and bus:

        on_execute: async (title, payload) -> bool — runs an approved
            proposal (Phase C wires a Mason agent here).
        dreamer_propose: async (context, max_proposals) -> List[Proposal] —
            LLM-driven proposal generation (a DreamerActor method). When
            absent, the engine falls back to threshold heuristics.
        on_stage: async (actor, text) — observability callback so
            interfaces can narrate the negotiation live.
        evaluation_timeout: seconds to wait for a foreman.decision before
            treating a proposal as rejected.
        """
        self._event_bus = event_bus
        self._dreamer_soul = dreamer_soul
        self._foreman_soul = foreman_soul
        self._diagnostics = diagnostics
        self._on_execute = on_execute
        self._dreamer_propose = dreamer_propose
        self._on_stage = on_stage
        self._evaluation_timeout = evaluation_timeout
        self._cycle = 0
        self._consecutive_failures = 0
        self._running = False
        self._results: List[AFKCycleResult] = []

    async def _stage(self, actor: str, text: str) -> None:
        """Narrate a negotiation stage to the observability callback."""
        if self._on_stage is None:
            return
        try:
            await self._on_stage(actor, text)
        except Exception:
            logger.exception("on_stage callback failed")

    @property
    def running(self) -> bool:
        return self._running

    @property
    def cycle_count(self) -> int:
        return self._cycle

    @property
    def results(self) -> List[AFKCycleResult]:
        return list(self._results)

    async def start(
        self,
        cycles: int = 0,
        max_duration_seconds: float = 0,
    ) -> None:
        """Start the AFK negotiation loop.

        Args:
            cycles: Number of cycles to run (0 = infinite).
            max_duration_seconds: Max wall-clock time (0 = no limit).
        """
        self._running = True
        start_time = _now()
        self._cycle = 0

        try:
            while self._running:
                self._cycle += 1

                if cycles > 0 and self._cycle > cycles:
                    logger.info("AFK: reached target cycle count (%d).", cycles)
                    break

                if max_duration_seconds > 0 and (_now() - start_time) > max_duration_seconds:
                    logger.info("AFK: reached max duration (%.0fs).", max_duration_seconds)
                    break

                result = await self._run_cycle()
                self._results.append(result)

                # Idle pause so empty cycles never busy-spin the CPU.
                if result.proposals_count == 0:
                    await asyncio.sleep(IDLE_CYCLE_PAUSE_SECONDS)

                # Safety valve
                if result.consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                    logger.warning(
                        "AFK: %d consecutive failures — safety pause %ds.",
                        result.consecutive_failures, SAFETY_PAUSE_SECONDS,
                    )
                    await asyncio.sleep(SAFETY_PAUSE_SECONDS)
                    self._consecutive_failures = 0

        except asyncio.CancelledError:
            logger.info("AFK protocol cancelled.")
        finally:
            self._running = False

    def stop(self) -> None:
        """Signal the AFK loop to stop."""
        self._running = False

    async def _run_cycle(self) -> AFKCycleResult:
        """Execute one full Dreamer→Foreman→Execute cycle."""
        cycle_start = _now()
        result = AFKCycleResult(cycle_number=self._cycle)

        # Stage 1: DREAM — Dreamer formulates proposals
        proposals = await self._dream_phase()
        result.proposals_count = len(proposals)

        for proposal in proposals:
            # Stage 2: EVALUATE — Foreman evaluates
            approved = await self._evaluate_phase(proposal)

            if approved:
                result.approved_count += 1

                # Stage 3: EXECUTE — run the approved proposal
                await self._stage("mason", f"building: {proposal.title}")
                success = await self._execute_phase(proposal)
                if success:
                    result.executed_count += 1
                    await self._stage("mason", f"✓ completed: {proposal.title}")
                else:
                    result.failed_count += 1
                    await self._stage("mason", f"✗ failed: {proposal.title}")
            else:
                result.failed_count += 1

        # Track consecutive failures for safety valve
        if result.executed_count == 0 and result.proposals_count > 0:
            self._consecutive_failures += 1
        else:
            self._consecutive_failures = 0

        result.consecutive_failures = self._consecutive_failures
        result.duration_seconds = _now() - cycle_start

        logger.info(
            "AFK cycle %d: %d proposals → %d approved → %d executed "
            "(%.1fs, consec_failures=%d)",
            self._cycle,
            result.proposals_count, result.approved_count, result.executed_count,
            result.duration_seconds, result.consecutive_failures,
        )

        return result

    async def _dream_phase(self) -> List[Proposal]:
        """Stage 1: Generate proposals.

        When a ``dreamer_propose`` callable is wired (the LLM-driven
        DreamerActor), the Dreamer persona reads a diagnostics digest and
        formulates proposals itself. Without it, the engine falls back to
        deterministic threshold heuristics over the same diagnostics.
        """
        proposals: List[Proposal] = []
        if self._dreamer_soul is None:
            return proposals

        max_proposals = self._dreamer_soul.behavioral_constraints.get(
            "max_proposals_per_cycle", 5
        )

        if self._dreamer_propose is not None:
            await self._stage("dreamer", "reviewing diagnostics and dreaming…")
            context = await self._build_dream_context()
            proposals = list(await self._dreamer_propose(context, max_proposals))
            for i, proposal in enumerate(proposals):
                if not proposal.proposal_id:
                    proposal.proposal_id = f"afk-{self._cycle}-{i + 1}"
            if proposals:
                for p in proposals:
                    await self._stage(
                        "dreamer",
                        f"proposes [{p.impact}/{p.complexity}] {p.title}",
                    )
            else:
                await self._stage("dreamer", "no proposals this cycle")
            return proposals[:max_proposals]

        if self._diagnostics is None:
            return proposals

        stats = await self._diagnostics.get_session_stats()

        # Proposal 1: High error/failure rate
        total_ops = stats.tool_success_count + stats.tool_failure_count
        if total_ops > 0 and stats.tool_failure_count / total_ops > 0.1:
            proposals.append(Proposal(
                title="Investigate elevated tool failure rate",
                description=(
                    f"Tool failure rate is {stats.tool_failure_count}/{total_ops} "
                    f"({stats.tool_failure_count / total_ops * 100:.0f}%). "
                    "Review recent tool calls and check for recurring errors."
                ),
                impact="medium",
                complexity="low",
                proposal_id=f"afk-{self._cycle}-failure-rate",
            ))

        # Proposal 2: High token cost
        if stats.token_cost > 0.01:
            proposals.append(Proposal(
                title="Optimize LLM token usage",
                description=(
                    f"Current session token cost: ${stats.token_cost:.4f}. "
                    f"Total LLM calls: {stats.total_llm_calls}. "
                    "Consider reducing context window or tuning prompts."
                ),
                impact="medium",
                complexity="medium",
                proposal_id=f"afk-{self._cycle}-token-cost",
            ))

        # Proposal 3: Slow tool execution
        if stats.avg_tool_latency_ms > 5000:
            proposals.append(Proposal(
                title="Audit slow tool calls",
                description=(
                    f"Average tool latency is {stats.avg_tool_latency_ms:.0f}ms. "
                    "Review recent tool traces for bottlenecks."
                ),
                impact="low",
                complexity="low",
                proposal_id=f"afk-{self._cycle}-slow-tools",
            ))

        # Proposal 4: Repeated failures from previous cycle
        if self._consecutive_failures > 2:
            prev_cycle = self._results[-1] if self._results else None
            if prev_cycle:
                proposals.append(Proposal(
                    title="Address recurring proposal failures",
                    description=(
                        f"{self._consecutive_failures} consecutive cycles with "
                        f"zero approved proposals. Last cycle: "
                        f"{prev_cycle.proposals_count} proposals, "
                        f"{prev_cycle.approved_count} approved."
                    ),
                    impact="high",
                    complexity="high",
                    proposal_id=f"afk-{self._cycle}-recurring-failures",
                ))

        # Return only the first N proposals per soul constraints
        return proposals[:max_proposals]

    async def _build_dream_context(self) -> str:
        """Digest diagnostics into a prompt-sized state report for the Dreamer."""
        if self._diagnostics is None:
            return (
                "No diagnostics bricks are seated this session, so there is "
                "no telemetry to mine. Propose only broadly useful, "
                "low-risk improvements — or nothing."
            )

        parts: List[str] = []
        try:
            stats = await self._diagnostics.get_session_stats()
            total_ops = stats.tool_success_count + stats.tool_failure_count
            parts.append(
                "Session stats: "
                f"{stats.total_llm_calls} LLM calls, "
                f"{total_ops} tool calls "
                f"({stats.tool_failure_count} failed), "
                f"avg tool latency {stats.avg_tool_latency_ms:.0f}ms, "
                f"token cost ${stats.token_cost:.4f}."
            )
        except Exception as exc:
            parts.append(f"Session stats unavailable: {exc}")

        try:
            events = await self._diagnostics.get_last_n_events(n=15)
            if events:
                lines = []
                for e in events:
                    etype = getattr(e, "event_type", "?")
                    payload = str(getattr(e, "payload", ""))[:120]
                    lines.append(f"- {etype}: {payload}")
                parts.append("Recent events:\n" + "\n".join(lines))
        except Exception as exc:
            parts.append(f"Recent events unavailable: {exc}")

        if self._results:
            last = self._results[-1]
            parts.append(
                f"Previous cycle: {last.proposals_count} proposals, "
                f"{last.approved_count} approved, {last.executed_count} "
                f"executed, {last.failed_count} failed."
            )

        return "\n\n".join(parts)

    async def _evaluate_phase(self, proposal: Proposal) -> bool:
        """Stage 2: Foreman evaluates a proposal.

        Checks against Foreman's behavioral constraints and AGENTS.md.
        Returns True if approved.
        """
        if self._foreman_soul is None:
            logger.info("No Foreman soul attached — rejecting '%s'.", proposal.title)
            return False

        max_attempts = min(
            self._foreman_soul.behavioral_constraints.get("max_subagents", 3),
            3,
        )

        for attempt in range(max_attempts):
            eval_event = BusEvent(
                event_type="foreman.evaluate_proposal",
                source_soul="dreamer",
                target_soul="foreman",
                payload={
                    "proposal": {
                        "title": proposal.title,
                        "description": proposal.description,
                        "impact": proposal.impact,
                        "complexity": proposal.complexity,
                        "proposal_id": proposal.proposal_id,
                    },
                    "attempt": attempt + 1,
                },
            )
            await self._event_bus.publish(eval_event)
            try:
                response = await asyncio.wait_for(
                    self._event_bus.consume("dreamer"),
                    timeout=self._evaluation_timeout,
                )
            except asyncio.TimeoutError:
                # An unanswered evaluation is an honest reject — never
                # fake a sign-off when no Foreman actor is on the bus.
                logger.info(
                    "Proposal '%s': no evaluator responded within %.0fs — rejected.",
                    proposal.title, self._evaluation_timeout,
                )
                await self._stage(
                    "foreman", f"no response in {self._evaluation_timeout:.0f}s — rejected: {proposal.title}"
                )
                return False

            decision = response.payload.get("decision", "reject")
            feedback = response.payload.get("feedback", "")

            if decision == "approve":
                logger.info("Proposal '%s' APPROVED.", proposal.title)
                await self._stage("foreman", f"APPROVED: {proposal.title}")
                return True
            elif decision == "defer" and attempt < max_attempts - 1:
                logger.info(
                    "Proposal '%s' DEFERRED (attempt %d/%d): %s",
                    proposal.title, attempt + 1, max_attempts, feedback,
                )
                await self._stage(
                    "foreman", f"DEFERRED: {proposal.title} — {feedback[:120]}"
                )
                # Carry the feedback forward without losing the original spec.
                proposal.description = (
                    f"{proposal.description}\n\nForeman feedback "
                    f"(attempt {attempt + 1}): {feedback}"
                )
                continue
            else:
                logger.info(
                    "Proposal '%s' REJECTED (attempt %d/%d): %s",
                    proposal.title, attempt + 1, max_attempts, feedback,
                )
                await self._stage(
                    "foreman", f"REJECTED: {proposal.title} — {feedback[:120]}"
                )
                return False

        return False

    async def _execute_phase(self, proposal: Proposal) -> bool:
        """Stage 3: Execute an approved proposal.

        Delegates to the on_execute callback, which the event loop
        provides to run the actual implementation.
        """
        if self._on_execute is None:
            logger.info("No on_execute handler — skipping execution.")
            return True

        timeout = 300

        try:
            result = await asyncio.wait_for(
                self._on_execute(proposal.title, {
                    "description": proposal.description,
                    "impact": proposal.impact,
                    "complexity": proposal.complexity,
                    "proposal_id": proposal.proposal_id,
                }),
                timeout=timeout,
            )
            success = result is not False
            logger.info(
                "Proposal '%s' EXECUTED (success=%s).",
                proposal.title, success,
            )
            return success

        except asyncio.TimeoutError:
            logger.error("Proposal '%s' TIMEOUT after %ds.", proposal.title, timeout)
            return False

        except Exception as exc:
            logger.exception("Proposal '%s' EXECUTION FAILED: %s", proposal.title, exc)
            return False
