from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from brikie.bricks.interface.event_bus import InternalEventBusBrick
from brikie.bricks.logging.base import LogEntry, LogLevel
from brikie.bricks.soul.base import SoulBrick
from brikie.bricks.soul.dreamer import Dreamer
from brikie.bricks.soul.sisyphus_orchestrator import SisyphusOrchestrator
from brikie.config.types import BusEvent

logger = logging.getLogger(__name__)

MAX_CONSECUTIVE_FAILURES = 5
SAFETY_PAUSE_SECONDS = 60


@dataclass
class Proposal:
    """A proposal generated by the Dreamer and evaluated by Sisyphus."""

    title: str = ""
    description: str = ""
    impact: str = "low"
    complexity: str = "low"
    proposal_id: str = ""
    status: str = "pending"


@dataclass
class AFKCycleResult:
    """Result of a single AFK negotiation cycle."""

    cycle_number: int = 0
    proposals_count: int = 0
    approved_count: int = 0
    executed_count: int = 0
    failed_count: int = 0
    duration_seconds: float = 0.0
    consecutive_failures: int = 0


def _now() -> float:
    import time
    return time.time()


class AFKProtocolEngine:
    """Orchestrates the Dreamer→Sisyphus AFK negotiation loop.

    The loop runs in three stages:
    1. DREAM — Dreamer reviews logs and formulates proposals
    2. EVALUATE — Sisyphus evaluates proposals against constraints
    3. EXECUTE — Sisyphus executes approved proposals

    Invariants:
    - Max 3 approval attempts per proposal
    - Max 3 sub-delegation depth per execution
    - 300s timeout per sub-task
    - Safety pause after 5 consecutive failures
    """

    def __init__(
        self,
        event_bus: InternalEventBusBrick,
        dreamer: Dreamer,
        sisyphus: SisyphusOrchestrator,
        on_execute: Optional[Callable[[str, Dict[str, Any]], Any]] = None,
    ) -> None:
        self._event_bus = event_bus
        self._dreamer = dreamer
        self._sisyphus = sisyphus
        self._on_execute = on_execute
        self._cycle = 0
        self._consecutive_failures = 0
        self._running = False
        self._results: List[AFKCycleResult] = []

    @property
    def running(self) -> bool:
        return self._running

    @property
    def cycle_count(self) -> int:
        return self._cycle

    @property
    def results(self) -> List[AFKCycleResult]:
        return list(self._results)

    async def start(
        self,
        cycles: int = 0,
        max_duration_seconds: float = 0,
    ) -> None:
        """Start the AFK negotiation loop.

        Args:
            cycles: Number of cycles to run (0 = infinite).
            max_duration_seconds: Max wall-clock time (0 = no limit).
        """
        self._running = True
        start_time = _now()
        self._cycle = 0

        try:
            while self._running:
                self._cycle += 1

                if cycles > 0 and self._cycle > cycles:
                    logger.info("AFK: reached target cycle count (%d).", cycles)
                    break

                if max_duration_seconds > 0 and (_now() - start_time) > max_duration_seconds:
                    logger.info("AFK: reached max duration (%.0fs).", max_duration_seconds)
                    break

                result = await self._run_cycle()
                self._results.append(result)

                # Safety valve
                if result.consecutive_failures >= MAX_CONSECUTIVE_FAILURES:
                    logger.warning(
                        "AFK: %d consecutive failures — safety pause %ds.",
                        result.consecutive_failures, SAFETY_PAUSE_SECONDS,
                    )
                    await asyncio.sleep(SAFETY_PAUSE_SECONDS)
                    self._consecutive_failures = 0

        except asyncio.CancelledError:
            logger.info("AFK protocol cancelled.")
        finally:
            self._running = False

    def stop(self) -> None:
        """Signal the AFK loop to stop."""
        self._running = False

    async def _run_cycle(self) -> AFKCycleResult:
        """Execute one full Dreamer→Sisyphus→Execute cycle."""
        cycle_start = _now()
        result = AFKCycleResult(cycle_number=self._cycle)

        # Stage 1: DREAM — Dreamer formulates proposals
        proposals = await self._dream_phase()
        result.proposals_count = len(proposals)

        for proposal in proposals:
            # Stage 2: EVALUATE — Sisyphus evaluates
            approved = await self._evaluate_phase(proposal)

            if approved:
                result.approved_count += 1

                # Stage 3: EXECUTE — run the approved proposal
                success = await self._execute_phase(proposal)
                if success:
                    result.executed_count += 1
                else:
                    result.failed_count += 1
            else:
                result.failed_count += 1

        # Track consecutive failures for safety valve
        if result.executed_count == 0 and result.proposals_count > 0:
            self._consecutive_failures += 1
        else:
            self._consecutive_failures = 0

        result.consecutive_failures = self._consecutive_failures
        result.duration_seconds = _now() - cycle_start

        logger.info(
            "AFK cycle %d: %d proposals → %d approved → %d executed "
            "(%.1fs, consec_failures=%d)",
            self._cycle,
            result.proposals_count, result.approved_count, result.executed_count,
            result.duration_seconds, result.consecutive_failures,
        )

        return result

    async def _dream_phase(self) -> List[Proposal]:
        """Stage 1: Dreamer reviews state and generates proposals.

        In a real implementation, the Dreamer would query logs, mempalace,
        and the wiki to formulate proposals. For now, this delegates to
        the event bus so a real Dreamer soul can respond.
        """
        request_event = BusEvent(
            event_type="dreamer.generate_proposals",
            source_soul="sisyphus_orchestrator",
            target_soul="dreamer",
            payload={
                "context": {
                    "cycle": self._cycle,
                    "consecutive_failures": self._consecutive_failures,
                },
                "max_proposals": self._dreamer.behavioral_constraints.get(
                    "max_proposals_per_cycle", 5
                ),
            },
        )
        await self._event_bus.publish(request_event)

        response = await self._event_bus.consume("sisyphus_orchestrator")

        raw = response.payload.get("proposals", [])
        proposals: List[Proposal] = []
        for item in raw:
            if isinstance(item, dict):
                proposals.append(Proposal(**item))
            elif isinstance(item, Proposal):
                proposals.append(item)
        return proposals

    async def _evaluate_phase(self, proposal: Proposal) -> bool:
        """Stage 2: Sisyphus evaluates a proposal.

        Checks against Sisyphus's behavioral constraints and AGENTS.md.
        Returns True if approved.
        """
        max_attempts = min(
            self._sisyphus.behavioral_constraints.get("max_subagents", 3),
            3,
        )

        for attempt in range(max_attempts):
            eval_event = BusEvent(
                event_type="sisyphus.evaluate_proposal",
                source_soul="dreamer",
                target_soul="sisyphus_orchestrator",
                payload={
                    "proposal": {
                        "title": proposal.title,
                        "description": proposal.description,
                        "impact": proposal.impact,
                        "complexity": proposal.complexity,
                        "proposal_id": proposal.proposal_id,
                    },
                    "attempt": attempt + 1,
                },
            )
            await self._event_bus.publish(eval_event)
            response = await self._event_bus.consume("dreamer")

            decision = response.payload.get("decision", "reject")
            feedback = response.payload.get("feedback", "")

            if decision == "approve":
                logger.info("Proposal '%s' APPROVED.", proposal.title)
                return True
            elif decision == "defer" and attempt < max_attempts - 1:
                logger.info(
                    "Proposal '%s' DEFERRED (attempt %d/%d): %s",
                    proposal.title, attempt + 1, max_attempts, feedback,
                )
                proposal.description = feedback
                continue
            else:
                logger.info(
                    "Proposal '%s' REJECTED (attempt %d/%d): %s",
                    proposal.title, attempt + 1, max_attempts, feedback,
                )
                return False

        return False

    async def _execute_phase(self, proposal: Proposal) -> bool:
        """Stage 3: Execute an approved proposal.

        Delegates to the on_execute callback, which the event loop
        provides to run the actual implementation.
        """
        if self._on_execute is None:
            logger.info("No on_execute handler — skipping execution.")
            return True

        timeout = 300

        try:
            result = await asyncio.wait_for(
                self._on_execute(proposal.title, {
                    "description": proposal.description,
                    "impact": proposal.impact,
                    "complexity": proposal.complexity,
                    "proposal_id": proposal.proposal_id,
                }),
                timeout=timeout,
            )
            success = result is not False
            logger.info(
                "Proposal '%s' EXECUTED (success=%s).",
                proposal.title, success,
            )
            return success

        except asyncio.TimeoutError:
            logger.error("Proposal '%s' TIMEOUT after %ds.", proposal.title, timeout)
            return False

        except Exception as exc:
            logger.exception("Proposal '%s' EXECUTION FAILED: %s", proposal.title, exc)
            return False
