"""HTTP Provider Bricks — LLM API translation layers.

Supports both OpenAI and Claude API formats out of the box.

API keys may be given literally or as an ``env:VAR_NAME`` reference,
resolved from the environment at ``init()`` — Build Sets generated by
the installer use the reference form so keys never land in JSON files.
"""

import asyncio
import logging
import os
from typing import Any, Dict, List, Optional

import httpx

from brikie.bricks.provider.base import ProviderBrick

logger = logging.getLogger(__name__)


class ProviderConnectionError(RuntimeError):
    """A provider endpoint could not be reached or rejected the request.

    Carries a human-readable message with a concrete next step — this is
    what end users see when their model server isn't running or their
    API key is wrong, so it must never be a bare traceback.
    """


class HTTPProvider(ProviderBrick):
    BRICK_NUMBER = "BRK-200"
    """Provider Brick that communicates with LLM APIs over HTTP.

    Supports both OpenAI and Anthropic (Claude) API formats.
    Configuration is driven by `api_format`, `model`, `api_key`,
    `base_url`, and optional `timeout`.
    """

    FORMAT_OPENAI = "openai"
    FORMAT_CLAUDE = "claude"

    def __init__(
        self,
        model: str = "gpt-4o",
        api_key: str = "sk-placeholder",
        base_url: str = "https://api.openai.com/v1",
        api_format: str = FORMAT_OPENAI,
        timeout: float = 120.0,
        max_retries: int = 2,
        retry_backoff: float = 2.0,
    ) -> None:
        super().__init__()
        self._name = "http_provider"
        self._model = model
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._api_format = api_format
        self._timeout = timeout
        self._max_retries = max_retries
        self._retry_backoff = retry_backoff
        self._client: Optional[httpx.AsyncClient] = None
        # Set in init() when api_key is an ``oauth:openai`` reference — a
        # dynamic, refreshable bearer instead of a static key.
        self._oauth_source: Optional[Any] = None

    def _is_oauth(self) -> bool:
        """True when this provider authenticates via OpenAI OAuth, not a key."""
        return (self._api_format == self.FORMAT_OPENAI
                and self._api_key.startswith("oauth:"))

    @property
    def name(self) -> str:
        return self._name

    @property
    def model(self) -> str:
        return self._model

    @property
    def base_url(self) -> str:
        return self._base_url

    def configure(
        self,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        api_key: Optional[str] = None,
        api_format: Optional[str] = None,
    ) -> None:
        """Override connection settings before ``init()`` is called."""
        if model:
            self._model = model
        if base_url:
            self._base_url = base_url.rstrip("/")
        if api_key:
            self._api_key = api_key
        if api_format:
            self._api_format = api_format

    @staticmethod
    def _resolve_ref(value: str) -> str:
        """Resolve ``env:VAR`` and ``env:VAR|fallback`` references.

        Plain values pass through untouched. ``env:VAR`` resolves to the
        variable's value (empty when unset); ``env:VAR|fallback`` falls
        back when the variable is unset — managed runtimes like
        OpenShell reroute inference by exporting the variable.
        """
        if not value.startswith("env:"):
            return value
        ref = value[4:]
        var, _, fallback = ref.partition("|")
        return os.environ.get(var, "").strip() or fallback

    def _resolve_api_key(self) -> str:
        """Resolve an ``env:VAR`` API-key reference from the environment."""
        resolved = self._resolve_ref(self._api_key)
        if self._api_key.startswith("env:") and not resolved:
            logger.warning(
                "API key references $%s but it is not set — requests "
                "to %s will likely be rejected. Export it and restart, "
                "or rerun `python3 -m brikie.install`.",
                self._api_key[4:].partition("|")[0], self._base_url,
            )
        return resolved

    async def init(self) -> None:
        """Initialize the async HTTP client."""
        self._base_url = self._resolve_ref(self._base_url).rstrip("/")
        if self._is_oauth():
            # OAuth: the Authorization header is dynamic (it refreshes), so
            # it is injected per-request in _post(), not baked into the client.
            from brikie.auth.openai_oauth import OpenAIOAuthSource
            self._oauth_source = OpenAIOAuthSource()
            headers = {"Content-Type": "application/json"}
            logger.info("HTTPProvider %s using OpenAI OAuth (ChatGPT sign-in).",
                        self._name)
        elif self._api_format == self.FORMAT_CLAUDE:
            api_key = self._resolve_api_key()
            headers = {
                "Content-Type": "application/json",
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            }
        else:
            api_key = self._resolve_api_key()
            headers = {
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            }

        self._client = httpx.AsyncClient(
            base_url=self._base_url,
            timeout=httpx.Timeout(self._timeout),
            headers=headers,
        )
        logger.info(
            "HTTPProvider %s initialized (%s / %s)",
            self._name,
            self._model,
            self._api_format,
        )
        await super().init()

    async def shutdown(self) -> None:
        """Close the async HTTP client."""
        if self._client:
            await self._client.aclose()
            self._client = None
        await super().shutdown()

    async def get_completion(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> tuple[str, List[Dict[str, Any]], Dict[str, Any]]:
        """Send a completion request and return (content, tool_calls, meta).

        ``meta`` carries side-channel data the kernel can render or log:
        ``reasoning`` (model thinking, if the API exposes it), ``usage``
        (token counts), and ``finish_reason``.

        Dispatches to the correct API format handler based on `api_format`.
        """
        if self._client is None:
            raise RuntimeError(f"HTTPProvider {self._name} not initialized.")

        if self._api_format == self.FORMAT_CLAUDE:
            return await self._call_claude(messages, tools)
        return await self._call_openai(messages, tools)

    # ------------------------------------------------------------------
    # Request plumbing — translate transport failures into human advice
    # ------------------------------------------------------------------

    async def _oauth_headers(self) -> Dict[str, str]:
        """Per-request Authorization for OAuth mode (empty for static keys).

        Returns a fresh bearer (refreshing if near expiry); a missing login
        is turned into a friendly, actionable error.
        """
        if self._oauth_source is None:
            return {}
        from brikie.auth.openai_oauth import OAuthError
        try:
            return await self._oauth_source.headers()
        except OAuthError as exc:
            raise ProviderConnectionError(f"OpenAI OAuth: {exc}") from exc

    async def _post(self, path: str, payload: Dict[str, Any]) -> httpx.Response:
        """POST to the provider, retrying transient failures.

        A slow/loading model or a momentary 5xx/429 shouldn't hard-kill an
        autonomous turn — those are retried with exponential backoff before
        the friendly error is raised. Auth/404/context errors aren't
        retried (retrying won't help).

        Raises:
            ProviderConnectionError: With a concrete, user-facing next
                step, after retries are exhausted.
        """
        last_exc: Exception | None = None
        auth_refreshed = False
        for attempt in range(self._max_retries + 1):
            try:
                extra_headers = await self._oauth_headers()
                response = await self._client.post(
                    path, json=payload, headers=extra_headers,
                )
                response.raise_for_status()
                return response
            except (httpx.ConnectError, httpx.ConnectTimeout) as exc:
                raise ProviderConnectionError(
                    f"can't reach your model server at {self._base_url} — is it "
                    f"running? (model: '{self._model}'). Start it, or run "
                    f"`python3 -m brikie.install` to pick a different provider."
                ) from exc
            except httpx.ReadTimeout as exc:
                last_exc = exc
                if attempt < self._max_retries:
                    delay = self._retry_backoff * (2 ** attempt)
                    logger.warning(
                        "Provider timed out (attempt %d/%d) — retrying in %.0fs",
                        attempt + 1, self._max_retries + 1, delay,
                    )
                    await asyncio.sleep(delay)
                    continue
                raise ProviderConnectionError(
                    f"{self._base_url} didn't answer within {self._timeout:.0f}s "
                    f"after {self._max_retries + 1} attempts — the model may be "
                    f"overloaded, or this machine too slow for '{self._model}'. "
                    f"Try again, or lower BRIKIE_CONTEXT_BUDGET if prompts are large."
                ) from exc
            except httpx.HTTPStatusError as exc:
                status = exc.response.status_code
                if (status == 401 and self._oauth_source is not None
                        and not auth_refreshed):
                    # An expired OAuth token — refresh once and retry before
                    # giving up. (A stale cached access token that the server
                    # rejected; the next attempt rebuilds the header.)
                    auth_refreshed = True
                    logger.info("OAuth token rejected (401) — refreshing.")
                    try:
                        await self._oauth_source.headers(force_refresh=True)
                    except Exception:
                        return self._raise_status_error(exc)
                    continue
                if status in (429, 500, 502, 503, 504) and attempt < self._max_retries:
                    last_exc = exc
                    delay = self._retry_backoff * (2 ** attempt)
                    logger.warning(
                        "Provider HTTP %d (attempt %d/%d) — retrying in %.0fs",
                        status, attempt + 1, self._max_retries + 1, delay,
                    )
                    await asyncio.sleep(delay)
                    continue
                return self._raise_status_error(exc)
        # Unreachable, but keeps type checkers happy.
        raise ProviderConnectionError(str(last_exc))

    def _raise_status_error(self, exc: httpx.HTTPStatusError) -> Any:
        """Map a non-retryable HTTP status to a friendly ProviderConnectionError."""
        status = exc.response.status_code
        if status in (401, 403):
            hint = (
                "your API key was rejected. Check the key (and that the "
                "right environment variable is exported), or rerun "
                "`python3 -m brikie.install`."
            )
        elif status == 404:
            hint = (
                f"the endpoint wasn't found — '{self._model}' may not "
                "exist on this server, or the base URL is wrong."
            )
        elif status == 429:
            hint = "you're being rate-limited. Wait a little and retry."
        else:
            body = exc.response.text[:200]
            hint = f"the server said: {body}" if body else "no detail given."
        raise ProviderConnectionError(
            f"{self._base_url} returned HTTP {status} — {hint}"
        ) from exc

    # ------------------------------------------------------------------
    # OpenAI API
    # ------------------------------------------------------------------

    async def _call_openai(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> tuple[str, List[Dict[str, Any]], Dict[str, Any]]:
        """Handle OpenAI-format /chat/completions endpoint."""
        payload: Dict[str, Any] = {
            "model": self._model,
            "messages": messages,
        }
        if tools:
            payload["tools"] = tools

        response = await self._post("/chat/completions", payload)
        data = response.json()

        choice = data["choices"][0]
        message = choice["message"]

        content = message.get("content", "") or ""
        reasoning = message.get("reasoning") or message.get("reasoning_content") or ""
        refusal = message.get("refusal") or ""
        if not content and refusal:
            content = f"[Refused] {refusal}"

        raw_calls: List[Dict[str, Any]] = list(message.get("tool_calls") or [])

        meta = {
            "reasoning": reasoning,
            "usage": data.get("usage") or {},
            "finish_reason": choice.get("finish_reason", ""),
        }

        logger.debug(
            "OpenAI response: content=%s finish=%s calls=%d usage=%s",
            repr(content)[:200], meta["finish_reason"],
            len(raw_calls), meta["usage"],
        )

        return content, raw_calls, meta

    # ------------------------------------------------------------------
    # Claude API
    # ------------------------------------------------------------------

    async def _call_claude(
        self,
        messages: List[Dict[str, Any]],
        tools: List[Dict[str, Any]],
    ) -> tuple[str, List[Dict[str, Any]], Dict[str, Any]]:
        """Handle Anthropic-format /v1/messages endpoint."""
        payload: Dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "max_tokens": 4096,
        }
        if tools:
            payload["tools"] = self._convert_tools_for_claude(tools)

        response = await self._post("/v1/messages", payload)
        data = response.json()

        content = ""
        reasoning = ""
        raw_calls: List[Dict[str, Any]] = []

        for block in data.get("content") or []:
            if block.get("type") == "text":
                content += block.get("text", "")
            elif block.get("type") == "thinking":
                reasoning += block.get("thinking", "")
            elif block.get("type") == "tool_use":
                raw_calls.append(block)

        usage = data.get("usage") or {}
        meta = {
            "reasoning": reasoning,
            # Normalize Anthropic usage keys to the OpenAI names the kernel reads.
            "usage": {
                "prompt_tokens": usage.get("input_tokens", 0),
                "completion_tokens": usage.get("output_tokens", 0),
            },
            "finish_reason": data.get("stop_reason", ""),
        }

        return content, raw_calls, meta

    @staticmethod
    def _convert_tools_for_claude(tools: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Convert OpenAI-style tool schemas to Claude format.

        OpenAI format:
        {
            "type": "function",
            "function": {
                "name": "calculator",
                "description": "...",
                "parameters": {"type": "object", "properties": {...}}
            }
        }

        Claude format:
        {
            "name": "calculator",
            "description": "...",
            "input_schema": {"type": "object", "properties": {...}}
        }
        """
        claude_tools: List[Dict[str, Any]] = []
        for tool in tools:
            if "function" in tool:
                func = tool["function"]
                claude_tools.append({
                    "name": func.get("name", ""),
                    "description": func.get("description", ""),
                    "input_schema": func.get("parameters", {}),
                })
            else:
                # Already in Claude format
                claude_tools.append(tool)
        return claude_tools
