"""Ninite-style installer generation for brikie.co.

Turns a brick selection into a Build Set JSON and a shell installer, and
renders the brick-picker web page. The brick catalog is imported from
``brikie.install`` — that module is the local reference implementation of
the same flow, so the two can never drift apart.
"""

from __future__ import annotations

import html
import json
import shlex
from typing import Any

from brikie.install import CATALOG, CatalogEntry

REPO_URL = "https://github.com/VeelaCleave/brikie"

ACCENT = "#ff762e"
ACCENT_SOFT = "#ff9e4f"
BORDER = "#7a3a1d"


class GenerationError(Exception):
    """Raised when a brick selection cannot become a valid Build Set."""


def flat_catalog() -> dict[str, CatalogEntry]:
    """The catalog flattened to a BRK-number → entry mapping."""
    return {entry.brk: entry for entries in CATALOG.values() for entry in entries}


def _block(brk: str) -> int:
    """The hundred-block of a BRK number (e.g. 'BRK-420' → 400)."""
    try:
        return int(brk[4:]) // 100 * 100
    except (ValueError, IndexError):
        return -1


def generate_buildset(brks: list[str], name: str) -> dict[str, Any]:
    """Build a Build Set manifest from a list of BRK numbers.

    Enforces the same minimum stack as ``BuildLoader.validate_minimum_stack``:
    at least one Provider (200-block) and one Interface (300-block) brick.

    Args:
        brks: Selected BRK numbers, in any order.
        name: Name for the generated Build Set.

    Raises:
        GenerationError: On unknown bricks, a bad name, or a selection
            below the minimum stack.
    """
    name = name.strip()
    if not name or not all(c.isalnum() or c in "-_" for c in name):
        raise GenerationError(
            "Build Set name must be non-empty alphanumeric (plus - and _)"
        )

    catalog = flat_catalog()
    seen: list[str] = []
    for brk in brks:
        if brk not in catalog:
            raise GenerationError(f"Unknown brick number: {brk!r}")
        if brk not in seen:
            seen.append(brk)

    blocks = {_block(brk) for brk in seen}
    missing = []
    if 200 not in blocks:
        missing.append("a Provider Brick (e.g. BRK-200)")
    if 300 not in blocks:
        missing.append("an Interface Brick (e.g. BRK-300)")
    if missing:
        raise GenerationError(
            "Selection does not meet the minimum stack: missing "
            + " and ".join(missing)
        )

    return {
        "name": name,
        "description": "Custom Build Set generated by brikie.co",
        "bricks": [
            (
                {"brk": brk, "config": dict(catalog[brk].config)}
                if catalog[brk].config else {"brk": brk}
            )
            for brk in seen
        ],
    }


def generate_install_sh(buildset: dict[str, Any]) -> str:
    """Render a POSIX shell installer that seats *buildset* locally.

    The script installs brikie from GitHub when it isn't importable, then
    writes the Build Set JSON into brikie's sets directory via Python (the
    only reliable way to locate the installed package).
    """
    name = buildset["name"]
    payload = json.dumps(buildset, indent=2)
    brick_count = len(buildset["bricks"])
    if "BRIKIE_BUILDSET_EOF" in payload:  # heredoc delimiter collision
        raise GenerationError("Build Set content collides with installer delimiter")

    return f"""#!/usr/bin/env sh
# brikie installer — generated by brikie.co
# Build Set: {name} ({brick_count} bricks)
set -eu

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 is required" >&2
    exit 1
fi

if ! python3 -c "import brikie" >/dev/null 2>&1; then
    echo "installing brikie from {REPO_URL} ..."
    python3 -m pip install {shlex.quote(f"git+{REPO_URL}")}
fi

python3 - <<'BRIKIE_BUILDSET_EOF'
import json
from brikie.install import SETS_DIR

build = json.loads({json.dumps(payload)})
path = SETS_DIR / (build["name"] + ".json")
path.write_text(json.dumps(build, indent=2) + "\\n")
print("build set written:", path)
BRIKIE_BUILDSET_EOF

echo ""
echo "  ▀▄▀▄▀▄  build set ready  ▄▀▄▀▄▀"
echo ""
echo "run your agent with:  brikie --set {name}"
"""


def render_index_html(registry_manifests: list[dict[str, Any]]) -> str:
    """Render the brikie.co brick-picker page.

    Args:
        registry_manifests: Latest manifests of all published community
            bricks, shown below the built-in catalog.
    """
    groups: list[str] = []
    for group, entries in CATALOG.items():
        rows = "\n".join(
            f'<label class="brick"><input type="checkbox" name="brick" '
            f'value="{html.escape(e.brk)}"{" checked" if e.default else ""}>'
            f'<span class="brk">{html.escape(e.brk)}</span>'
            f'<span class="label">{html.escape(e.label)}</span>'
            f'<span class="blurb">{html.escape(e.blurb)}</span></label>'
            for e in entries
        )
        groups.append(
            f'<fieldset><legend>{html.escape(group)}</legend>{rows}</fieldset>'
        )

    if registry_manifests:
        rows = "\n".join(
            f'<li><span class="brk">{html.escape(m["name"])}</span> '
            f'v{html.escape(m["version"])} '
            f'<span class="blurb">[{html.escape(m["type"])}] '
            f'{html.escape(m.get("description", ""))}</span></li>'
            for m in registry_manifests
        )
        community = (
            "<h2>community bricks in this registry</h2>"
            "<p class='hint'>install at runtime with the registry_install tool</p>"
            f"<ul class='community'>{rows}</ul>"
        )
    else:
        community = (
            "<h2>community bricks in this registry</h2>"
            "<p class='hint'>none published yet — be the first: "
            "<code>registry_publish</code></p>"
        )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>brikie.co — build your agent, brick by brick</title>
<style>
  body {{ background:#16100b; color:#e8d5c4; font-family:ui-monospace,monospace;
         max-width:880px; margin:2rem auto; padding:0 1rem; }}
  h1 {{ color:{ACCENT}; }} h2 {{ color:{ACCENT_SOFT}; margin-top:2rem; }}
  .tagline {{ color:#c8855a; font-style:italic; }}
  fieldset {{ border:1px solid {BORDER}; margin:1rem 0; padding:.6rem 1rem; }}
  legend {{ color:{ACCENT_SOFT}; font-weight:bold; padding:0 .5rem; }}
  .brick {{ display:block; padding:.25rem 0; cursor:pointer; }}
  .brk {{ color:{ACCENT}; margin:0 .6rem; }}
  .label {{ font-weight:bold; margin-right:.6rem; }}
  .blurb {{ color:#9c7a5f; }}
  .hint {{ color:#9c7a5f; }}
  input[type=text] {{ background:#241a12; color:#e8d5c4;
         border:1px solid {BORDER}; padding:.4rem; }}
  pre {{ background:#241a12; border:1px solid {BORDER}; padding:1rem;
         overflow-x:auto; white-space:pre-wrap; word-break:break-all; }}
  a {{ color:{ACCENT_SOFT}; }}
  ul.community {{ list-style:none; padding-left:0; }}
</style>
</head>
<body>
<h1>▀▄▀▄▀▄ brikie ▄▀▄▀▄▀</h1>
<p class="tagline">build your agent &middot; brick by brick</p>

<form id="picker">
{''.join(groups)}
<p><label>build set name:
  <input type="text" id="setname" value="custom" size="20"></label></p>
</form>

<h2>your installer</h2>
<pre id="cmd"></pre>
<p><a id="buildset-link" href="#">inspect the generated buildset.json</a></p>

{community}

<script>
function update() {{
  const picked = [...document.querySelectorAll('input[name=brick]:checked')]
    .map(b => b.value);
  const name = document.getElementById('setname').value || 'custom';
  const qs = 'bricks=' + picked.join(',') + '&name=' + encodeURIComponent(name);
  const base = window.location.origin;
  document.getElementById('cmd').textContent =
    'curl -fsSL "' + base + '/install.sh?' + qs + '" | sh';
  document.getElementById('buildset-link').href = '/buildset.json?' + qs;
}}
document.getElementById('picker').addEventListener('change', update);
document.getElementById('setname').addEventListener('input', update);
update();
</script>
</body>
</html>
"""
